name: Perks
authors: [N3wton, wman2]
main: me.wman.perks.Perks
version: 1.9
website: www.mcbadgercraft.com
description: A plugin containing all the Donator perks for McBadgerCraft
softdepend: [Spout, MobArena, dynmap, Multiverse-Core, Vault]
depend: [BukkitDatabaseManager]

commands:
   perks:
      description: Lists all player perks.
      usage: /<command>
      
   fly:
      description: Turns fly mode on.
      usage: /<command>
  
   gmtoggle:
      description: Toggles a players gamemode
      usage: /<command>

   gm:
      description: Lets you see a players gamemode
      usage: /<command> [player]
   
   creative:
      description: puts you into creative mode
      usage: /<command>

   survival:
      description: puts you into survival mode
      usage: /<command>
      
   tpr:
      description: Request to be teleported to player
      usage: /<command> <player>
      
   tphr:
      description: Request to teleport a player to you
      usage: /<command> <player>
      
   put:
      description: Put a player where you are looking
      usage: /<command> <player>
      
   tpa:
      description: Accept a players teleport request
      usage: /<command> [player]
      
   tpd:
      description: Accept a players teleport request
      usage: /<command> [player]
     
   death:
      description: Teleport to your last death point
      usage: /<command>
       
   home:
      description: Teleport you to your current worlds home
      usage: /<command> [world]
      
   sethome:
      description: Sets your home in the current world
      usage: /<command>
      
   build:
      description: Teleport you to your current build location
      usage: /<command>
      
   setbuild:
      description: Sets your build location
      usage: /<command>
  
   promote:
      description: promote command
      usage: /<command> <player> [ladder]
      
   demote:
      description: demote command
      usage: /<command> <player> [ladder]
      
   vanish:
      description: lets you vanish
      usage: /<command>
      
   list:
      description: lists all online players
      aliases: [who,players]
      usage: /<command>
      
   land:
      description: forces your fly mode off
      usage: /<command>
      
   item:
      description: gives yourself items 
      usage: /<command> [-do] <item> [ammount] [player]
      aliases: [i]
   
   afk:
      description: teleports you to your afk spot
      usage: /<command>
      
   tphere:
      description: teleports another player here
      aliases: [s, bring]
      usage: /<command> <target>
   
   tp:
      description: teleports you to another player
      usage: /<command> <target>
   
   kit:
      description: kit commands
      usage: /<command> [target]  
      
   clear:
      description: Clears a players inventory
      usage: /<command> [-sa] [player]
      
   time:
      description: changes the time
      usage: /<command> <time> [world]
      
   weather:
      description: changes the weather
      usage: /<command> [-s] <state> [duration] [world]
      
   perksadmin:
      description: admin commands
      aliases: [padmin]
      usage: /<command> <argument>
      
   debug:
      description: debug stuff
      usage: /<command> <clock/info>
      
   lookup:
      description: lookup a player
      usage: /<command> <target>
      
   ping:
      description: pong
      usage: /<command>
      
   spawn:
      description: teleports you to spawn
      usage: /<command>
      
   setspawn:
      description: sets the spawn
      usage: /<command>
      
   spectate:
      description: spectate a player
      usage: /<command> <target>
      
   slap:
      description: slap
      usage: /<command> [-hvs] <target>
      
   rocket:
      description: rocket
      usage: /<command> [-hs] <target>
      
   thor:
      description: grants the use of thors hammer
      usage: /<command>
      
   shock:
      description: shocks a player
      usage: /<command> [-s] <target>
      
   stop:
      description: Tops the server taking an optional delay time
      usage: /<command> [time]
      
   hide:
      description: hide's yourself from livemap
      usage: /<command>
      
   show:
      description: show's yourself on livemap
      usage: /<command>
 
   setspawn:
      description: sets the spawn for the world you are in
      usage: /<command>