name: bConomy
authors: [N3wton, wman2]
main: uk.badger.bConomy.bConomy
version: 1.0
website: www.mcbadgercraft.com
description: A simple econmy plugin for bukkit
softdepend: [PermissionsEx]
depend: [BukkitDatabaseManager]

commands:
   money:
      description: Access all money commands
      usage: /<command>