name: bConomy
authors: [N3wton, wman2]
main: uk.thecodingbadgers.bConomy.bConomy
version: 1.0
website: www.mcbadgercraft.com
description: A simple econmy plugin for bukkit

depend: [bDatabaseManager, Vault]
load: startup

commands:
   money:
      description: Access all money commands
      usage: /<command>